name: edtech_application
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: 6.1.0
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
  otp_text_field: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/cardImages/img1.svg
    - assets/cardImages/img2.svg
    - assets/svgIcons/icon1.svg
    - assets/svgIcons/icon2.svg
    - assets/svgIcons/icon3.svg
    - assets/svgIcons/icon4.svg

    - assets/svgImg/login.svg
    - assets/svgImg/register.svg
    - assets/svgImg/otp.svg

    - assets/svgIcons/google.svg
